### ISSUE TITLE
Création d'un nouveau sous-module à partir de m_sipaf

### ISSUE THREAD

**Issue by marineteneur** [PnX-SI/gn_modulator#99]
Bonjour, 

J'essaye de créer un sous-module modulator, mais n'ayant pas vraiment de bases en programmation de module, j'ai décidé de reprendre le code du module m_sipaf pour l'adapter à mon modèle de données. 
Pour l'instant je n'ai adapté que les fichiers définissant les passages à faune et ai laissé les diagnostiques tels qu'ils sont (pour une modification postérieure).
Je suis enfin arrivée au bout de tous les fichiers de configuration mais l'installation du sous-module ne fonctionne pas et je n'arrive pas à trouver pourquoi. 

Pourriez-vous m'aider à comprendre ?

Merci d'avance !

Marine

**La commande d'installation du sous-module** : 
(venv) geonatureadmin@srv-geonature2023:~$ geonature modulator install -p /home/geonatureadmin/gn_modulator/contrib/m_tox
/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/sqlalchemy/orm/mapper.py:1841: SAWarning: Property TBaseVisits.dataset on mapped class TBaseVisits->t_base_visits being replaced with new property TBaseVisits.dataset; the old property will be discarded
  util.warn(
Obtaining file:///home/geonatureadmin/gn_modulator/contrib/m_tox
  Preparing metadata (setup.py) ... done
Installing collected packages: m-tox
  Attempting uninstall: m-tox
    Found existing installation: m-tox 1.0.0
    Uninstalling m-tox-1.0.0:
      Successfully uninstalled m-tox-1.0.0
  Running setup.py develop for m-tox
Successfully installed m-tox-1.0.0
Traceback (most recent call last):
  File "/home/geonatureadmin/geonature/backend/venv/bin/geonature", line 8, in <module>
    sys.exit(main())
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/flask/cli.py", line 357, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/geonatureadmin/geonature/backend/venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/geonatureadmin/gn_modulator/backend/gn_modulator/commands.py", line 32, in cmd_install_module
    return ModuleMethods.install_module(module_code, module_path, force)
  File "/home/geonatureadmin/gn_modulator/backend/gn_modulator/module/commands.py", line 127, in install_module
    cls.init_module_config(module_code)
  File "/home/geonatureadmin/gn_modulator/backend/gn_modulator/module/config/base.py", line 50, in init_module_config
    module_config["registred"] = module_db is not None
TypeError: 'NoneType' object does not support item assignment

**Le fichier du module** : 
[m_tox_v0.zip](https://github.com/PnX-SI/gn_modulator/files/14946975/m_tox_v0.zip)

**Le schéma sur lequel est basé le module actuellement** : 
![image](https://github.com/PnX-SI/gn_modulator/assets/115530181/df1b685c-9459-49be-bcb7-35c3d72c5f7d)

**Comment by camillemonchicourt** [comment]
Bonjour, MODULATOR est fonctionnel, mais il nécessite des compétences en développement pour pouvoir créer un nouveau module.

Une présentation globale du fonctionnement technique ait ici : https://github.com/PnX-SI/gn_modulator/blob/main/doc/presentation.md

Mais pour que cela soit facilement utilisable par d'autres, il faudrait faire plus de documentation, et potentiellement simplifier la configuration et l'ajout de tables et de champs.

Nous n'avons actuellement pas de ressources pour maintenir ou faire évoluer ce module.
